export App from './App/App';
export Home from './Home/Home';
export About from './About/About';
export Work from './Work/Work';
export Contact from './Contact/Contact';
export Resume from './Resume/Resume';
//export Login from './Login/Login';
//export LoginSuccess from './LoginSuccess/LoginSuccess';
//export NotFound from './NotFound/NotFound';