
//LOAD USER 
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE';

//LOAD HOME GALLERY
export const LOAD_HOMEGALLERY_REQUEST = 'LOAD_HOMEGALLERY_REQUEST';
export const LOAD_HOMEGALLERY_SUCCESS = 'LOAD_HOMEGALLERY_SUCCESS';
export const LOAD_HOMEGALLERY_FAILURE = 'LOAD_HOMEGALLERY_FAILURE';

//LOAD COVERS GALLERY
export const LOAD_COVERSGALLERY_REQUEST = 'LOAD_COVERSGALLERY_REQUEST';
export const LOAD_COVERSGALLERY_SUCCESS = 'LOAD_COVERSGALLERY_SUCCESS';
export const LOAD_COVERSGALLERY_FAILURE = 'LOAD_COVERSGALLERY_FAILURE';

//LOAD NYC GALLERY
export const LOAD_NYCGALLERY_REQUEST = 'LOAD_NYCGALLERY_REQUEST';
export const LOAD_NYCGALLERY_SUCCESS = 'LOAD_NYCGALLERY_SUCCESS';
export const LOAD_NYCGALLERY_FAILURE = 'LOAD_NYCGALLERY_FAILURE';

//LOAD PEOPLE GALLERY
export const LOAD_PEOPLEGALLERY_REQUEST = 'LOAD_PEOPLEGALLERY_REQUEST';
export const LOAD_PEOPLEGALLERY_SUCCESS = 'LOAD_PEOPLEGALLERY_SUCCESS';
export const LOAD_PEOPLEGALLERY_FAILURE = 'LOAD_PEOPLEGALLERY_FAILURE';

//LOAD FIXEDLINK GALLERY
export const LOAD_FIXEDLINKGALLERY_REQUEST = 'LOAD_FIXEDLINKGALLERY_REQUEST';
export const LOAD_FIXEDLINKGALLERY_SUCCESS = 'LOAD_FIXEDLINKGALLERY_SUCCESS';
export const LOAD_FIXEDLINKGALLERY_FAILURE = 'LOAD_FIXEDLINKGALLERY_FAILURE';

//LOAD STREETS GALLERY
export const LOAD_STREETSGALLERY_REQUEST = 'LOAD_STREETSGALLERY_REQUEST';
export const LOAD_STREETSGALLERY_SUCCESS = 'LOAD_STREETSGALLERY_SUCCESS';
export const LOAD_STREETSGALLERY_FAILURE = 'LOAD_STREETSGALLERY_FAILURE';
